[package]
name = "ftrd"
version = "0.1.0"
edition = "2015"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
libc = "0.2.158"
nix = "0.26.2"
