# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

>>>>>>> upstream/master
name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.18', '1.19', '1.20' ]
    steps:
      - uses: actions/checkout@v3
      - name: Test Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
  
      - name: Build
        run: make

      - name: Run tests
        run: make test
